# Exemplo de Deployment que permite explorar arquivos em um volume
# A ideia é colocar em claimName o nome do volume claim que deseja explorar
# Documentação do FileGator: https://filegator.io/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-private-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filegator/filegator
        resources: {}
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /var/www/filegator/private # para armazenar as configurações de usuários
            name: private-pv
          ########
          # mapeamentos dos volumes para gerenciamento
          # cada entrada aqui deve possuir uma correspondente em volumes:
          ########
          - mountPath: /var/www/filegator/repository/weilplace
            name: weilplace-pv
          - mountPath: /var/www/filegator/repository/kubectl-home
            name: kubectl-home-pv
      volumes:
      - name: private-pv
        persistentVolumeClaim:
          claimName: filebrowser-private-pvc
      - name: weilplace-pv
        persistentVolumeClaim:
          claimName: weilplace-pvc
      - name: kubectl-home-pv
        persistentVolumeClaim:
          claimName: kubectl-home-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
spec:
  type: NodePort
  selector:
    app: filebrowser
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30021